"""changedreftok

Revision ID: 04b2612feaf3
Revises: 7a348a0311ff
Create Date: 2024-04-29 12:25:33.185124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b2612feaf3'
down_revision = '7a348a0311ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_refresh_token_username'), 'refresh_token', ['username'], unique=False)
    op.drop_column('refresh_token', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_refresh_token_username'), table_name='refresh_token')
    op.drop_column('refresh_token', 'username')
    # ### end Alembic commands ###
