"""vimeo_thumb

Revision ID: 15095254bb47
Revises: 71874e715fdf
Create Date: 2024-07-31 11:24:58.809532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15095254bb47'
down_revision = '71874e715fdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_item_bucket_id'), 'item_bucket', ['id'], unique=False)
    op.add_column('item_vimeo', sa.Column('thumbnail', sa.String(), nullable=True))
    op.create_index(op.f('ix_item_vimeo_id'), 'item_vimeo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_vimeo_id'), table_name='item_vimeo')
    op.drop_column('item_vimeo', 'thumbnail')
    op.drop_index(op.f('ix_item_bucket_id'), table_name='item_bucket')
    # ### end Alembic commands ###
