"""item_link

Revision ID: 286a3fff2527
Revises: 37a576518b9d
Create Date: 2024-08-07 16:09:46.893253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '286a3fff2527'
down_revision = '37a576518b9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_bucket_id', sa.Integer(), nullable=True),
    sa.Column('item_vimeo_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['item_bucket_id'], ['item_bucket.id'], name='item_link_item_bucket_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_vimeo_id'], ['item_vimeo.id'], name='item_link_item_vimeo_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index(op.f('ix_item_link_id'), 'item_link', ['id'], unique=False)
    op.add_column('gallery_link', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('gallery_link', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gallery_link', 'expiration_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('gallery_link', 'is_active')
    op.drop_index(op.f('ix_item_link_id'), table_name='item_link')
    op.drop_table('item_link')
    # ### end Alembic commands ###
