"""gallery-link

Revision ID: 37a576518b9d
Revises: aa0c25e89bb1
Create Date: 2024-08-02 15:26:03.268170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a576518b9d'
down_revision = 'aa0c25e89bb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], name='gallery_link_gallery_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index(op.f('ix_gallery_link_id'), 'gallery_link', ['id'], unique=False)
    op.add_column('gallery_item', sa.Column('item_order', sa.Integer(), nullable=False))
    op.drop_column('gallery_item', 'order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery_item', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('gallery_item', 'item_order')
    op.drop_index(op.f('ix_gallery_link_id'), table_name='gallery_link')
    op.drop_table('gallery_link')
    # ### end Alembic commands ###
