"""reftok

Revision ID: 7a348a0311ff
Revises: 95b261651d94
Create Date: 2024-04-28 14:58:32.466896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a348a0311ff'
down_revision = '95b261651d94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('user_agent', sa.String(), nullable=True))
    op.add_column('refresh_token', sa.Column('ip_address', sa.String(), nullable=True))
    op.drop_column('refresh_token', 'headers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('headers', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('refresh_token', 'ip_address')
    op.drop_column('refresh_token', 'user_agent')
    # ### end Alembic commands ###
