"""video-dimensions

Revision ID: 8d6f3ccf7a0e
Revises: d8b6db641ad2
Create Date: 2024-08-14 10:58:53.184784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6f3ccf7a0e'
down_revision = 'd8b6db641ad2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_vimeo', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('item_vimeo', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_vimeo', 'height')
    op.drop_column('item_vimeo', 'width')
    # ### end Alembic commands ###
