"""media-url

Revision ID: 97f6efd6f60c
Revises: d178b711003b
Create Date: 2024-05-19 17:01:46.957185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f6efd6f60c'
down_revision = 'd178b711003b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_config', sa.Column('bucket_name', sa.String(), nullable=True))
    op.add_column('source_config', sa.Column('media_prefix', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_config', 'media_prefix')
    op.drop_column('source_config', 'bucket_name')
    # ### end Alembic commands ###
