"""grid

Revision ID: a54289211d3b
Revises: 97f6efd6f60c
Create Date: 2024-05-21 12:50:39.287437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54289211d3b'
down_revision = '97f6efd6f60c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_config', sa.Column('grid_view', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_config', 'grid_view')
    # ### end Alembic commands ###
