"""sources

Revision ID: ab3bf635a355
Revises: 04b2612feaf3
Create Date: 2024-04-30 17:59:56.434197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab3bf635a355'
down_revision = '04b2612feaf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('access_key_id', sa.String(), nullable=True),
    sa.Column('secret_access_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_config_id'), 'source_config', ['id'], unique=False)
    op.drop_index('ix_refresh_token_id', table_name='refresh_token')
    op.drop_index('ix_refresh_token_username', table_name='refresh_token')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='refresh_token_pkey')
    )
    op.create_index('ix_refresh_token_username', 'refresh_token', ['username'], unique=False)
    op.create_index('ix_refresh_token_id', 'refresh_token', ['id'], unique=False)
    op.drop_index(op.f('ix_source_config_id'), table_name='source_config')
    op.drop_table('source_config')
    # ### end Alembic commands ###
