"""date_created

Revision ID: d8b6db641ad2
Revises: ac7777f70b06
Create Date: 2024-08-10 21:31:59.377770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b6db641ad2'
down_revision = 'ac7777f70b06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'auth_user', 'auth_user', ['created_by_id'], ['id'])
    op.add_column('gallery_item', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('gallery_item', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gallery_item', 'auth_user', ['created_by_id'], ['id'])
    op.add_column('saved_item_bucket', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('saved_item_vimeo', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('source_bucket', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('source_vimeo', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tag', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tag', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tag', 'auth_user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'created_by_id')
    op.drop_column('tag', 'date_created')
    op.drop_column('source_vimeo', 'date_created')
    op.drop_column('source_bucket', 'date_created')
    op.drop_column('saved_item_vimeo', 'date_created')
    op.drop_column('saved_item_bucket', 'date_created')
    op.drop_constraint(None, 'gallery_item', type_='foreignkey')
    op.drop_column('gallery_item', 'created_by_id')
    op.drop_column('gallery_item', 'date_created')
    op.drop_constraint(None, 'auth_user', type_='foreignkey')
    op.drop_column('auth_user', 'created_by_id')
    # ### end Alembic commands ###
