"""saved-items

Revision ID: d96134c53e9b
Revises: 286a3fff2527
Create Date: 2024-08-09 09:52:01.645007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96134c53e9b'
down_revision = '286a3fff2527'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_item_bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_bucket_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['item_bucket_id'], ['item_bucket.id'], name='saved_item_bucket_item_bucket_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_item_bucket_id'), 'saved_item_bucket', ['id'], unique=False)
    op.create_table('saved_item_vimeo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_vimeo_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['item_vimeo_id'], ['item_vimeo.id'], name='saved_item_vimeo_item_vimeo_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_item_vimeo_id'), 'saved_item_vimeo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_item_vimeo_id'), table_name='saved_item_vimeo')
    op.drop_table('saved_item_vimeo')
    op.drop_index(op.f('ix_saved_item_bucket_id'), table_name='saved_item_bucket')
    op.drop_table('saved_item_bucket')
    # ### end Alembic commands ###
